### ISSUE TITLE
Is code for comparison methods available

### ISSUE THREAD

**Issue by zdk123** [kfattila/LZW-Kernel#1]
I came across your very nice Bioinformatics paper for this method. I was wondering if you also have implementations for the other methods available, since I'm interested in a similar comparison (in a different problem domain). You mention the source of the Local alignment and mismatch kernels but not, for example, SAM & Fisher.

Thanks!

**Comment by kfattila** [comment]
I do not have code for SAM & Fisher method. We took the results directly form other papers. The source code for the Mismatch kernel along with spectrum kernel are available and it is easy to use. There are several similarity or distance functions implemented in the nice toolbox Alfree.

**Comment by zdk123** [comment]
ok thanks!
